### ISSUE TITLE
Zoom factor indicator doesn't react to zooming.

### ISSUE THREAD

**Issue by xanfus** [ankitrohatgi/WebPlotDigitizer#123]
![image](https://user-images.githubusercontent.com/5682375/33657746-48ac8702-da8b-11e7-96a5-4a349fa0e104.png)
![image](https://user-images.githubusercontent.com/5682375/33657779-5fa5aa74-da8b-11e7-98c5-a9b118165105.png)

**Comment by ankitrohatgi** [comment]
This is intentional and so I'd say it's working as I expected. You can manually change the zoom scale by pressing that little gear icon on the top right in the zoom view and change the number.

The reason why I didn't make it a simple linear scaling as it did not work well across images of different resolutions and the different size of features. So this view is not really a "zoom factor indicator", but just an aid to help you get a differently scaled view of the same area.
