### ISSUE TITLE
Feature request: add option extract data using a constant Y step instead of a constant X step

### ISSUE THREAD

**Issue by p-costa** [ankitrohatgi/WebPlotDigitizer#232]
This may be quite useful for improving the data extraction from plots that show strong variations in X, but not in Y, specially when interpolation is also used (correct ?). An hacky way of doing it would be rotating the figure 90 degrees and swapping the axes, but this seems like a straightforward addition to the tool.

Thanks @ankitrohatgi for this awesome tool, by the way!

**Comment by nbehrnd** [comment]
Your suggestion does not read like a simple change of increments Δx and Δy

![increment](https://user-images.githubusercontent.com/19709084/95482712-f1f72500-097d-11eb-8038-37c578a273ea.png)

which may be set independently from each other (compare with the data in [test_set.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/5349133/test_set.zip) from the default plot).  Thus I suggest you add an illustration where your experience using the digitizer may be improved.  If not by a `.png` easily embedded into a comment, you equally may share the file in question within an `.zip` archive.

**Comment by p-costa** [comment]
Thanks for your response. When one needs to use interpolation and smoothing in certain curves there the variations in X are very large, using a constant step in Y can be quite advantageous. I have sumbled accross an example on my work recently, but now I attach the default preview from webplotdigitizer, but rotated 90 degrees.

PS: In this particular example, other extractions will work quite well, but I am specifically talking about cases where smoothing is desired.

![Screenshot from 2020-10-08 16-09-36](https://user-images.githubusercontent.com/29615530/95485108-ccb7e600-0980-11eb-92a5-887444d253b4.png)

**Comment by nbehrnd** [comment]
If the aim is / was to trace the blue curve, than the image displays only one point I would consider as match with this reference.  The ondulation of the blue curve equally represents the problem to yield for many points along the abcissa more than one on the ordinate.  I _speculate_ it were nice if the digitizer could recognize points of inflection to increase in these regions the number of points to model the blue curve.

**Comment by p-costa** [comment]
So if I understand correctly it is a problem of having more than one possible solution for each value of X, and not how large the variation of it is. For reference, below is a simpler example of a plot where I also got much better results (extracting the data from the solid line) after rotating the figure 90 degrees, perhaps for the same reason. I think that for cases like this, having the choice of a `Y step w/ interpolation` would be nice.

![Screenshot from 2020-10-08 19-49-07](https://user-images.githubusercontent.com/29615530/95506848-09470a00-09a0-11eb-9020-b7c664d6ca49.png)

**Comment by nbehrnd** [comment]
Indeed I do perceive the work with the digitizer the best if the relationship between points on abcissa and ordinate is strict bijective.  If this is not the case, the safest way I identified was to perform the scrutinies in sections -- which is eased because one project may accommodate multiple datasets at once.  And the digitizer does not mind if these data sets are all about «the blue curve», or (blue curve, orange one, etc.), it is up to the user to define start, end, increment and name of the individual trace.

As an example, I rotated the digitizer's default x-y plot by 90 degrees.  Using the default Δx and Δy increment of 10 and normal pen width, I followed the blue line in 12 sections, percolating down the funnel.  Prior to exporting the project I took screen photos of the individual sections, stitched them together into the following animated `.gif` to illustrate my processing:

![all_together](https://user-images.githubusercontent.com/19709084/95517539-b9bd0a00-09b0-11eb-9cdc-e6895ea4a412.gif)


Frame No 13 seen longer than the other twelve displays all sections simultaneously.  The project's `.tar`, the exported `.cvs` and screen photos are shared ([test_case.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/5351451/test_case.zip)).  Note that I took the liberty to have an abcissa running from reference point X1 on the left bottom corner (plus 2) to X2 on the right bottom corner (minus 2), while both references about Y are on the right vertical at 0 or 6.

Thus, if you have diagrams like the one in your comment by Oct 8, 7:55 PM UTC, I would seek to establish / restore the bijective relationship between abscissa and ordinate in first place. The freely available tool [Imagemagick](https://imagemagick.org/index.php) for example allows to turn the image quickly by an instruction on the CLI in the pattern of 

`convert input.png -rotate 90 output.png`

(If you prefer a GUI, [Xnconvert](https://www.xnview.com/en/xnconvert/), or [irfanview](https://www.irfanview.com/) may offer this as well).  The image shall then submitted to the digitizer, and the _intermediate_ numeric results are then subject to a coordinate transformation.  Thankfully, the transformation matrix is simplified because both source and target coordinate system are 2D and cartesian ([example](https://farside.ph.utexas.edu/teaching/336k/Newton/node153.html)). This standard method, sometimes adjusting the increments for a curve to trace (which may differ from dataset to dataset within one project) offered me extractions which were _good enough_, thus I can't share experience with the interpolation of the points.

**Comment by p-costa** [comment]
Thanks for the detailed answer and suggestions. I played around and extracting the data box-by-box using the `x-step with interpolation` method seems to capture the data well as long as the section crosses lines of constant x only once. Finding the optimal rotation seems also like a nice suggestion, thanks for that.

I think that in the most common use cases one would just need to rotate by 90 degrees, so having the option for sweeping in Y instead of X would relieve that small effort.

**Comment by ankitrohatgi** [comment]
Hi - you can always pick "x" axis to be the one that is along the vertical direction and "y" as horizontal and use the interpolation without having to rotate the image etc. The X and Y axes don't need to be aligned to X and Y in pixels.

**Comment by ankitrohatgi** [comment]
Just tried on one of the above images:

![image](https://user-images.githubusercontent.com/415640/95558843-b7b47480-09cb-11eb-9cb9-8955b48e17f0.png)

[vertical_plot.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/5353422/vertical_plot.zip)

**Comment by p-costa** [comment]
This actually does exactly what I was asking. Thank you! Closing.
