### ISSUE TITLE
Bug: Non-Linear Axis in Spectroscopy Plot

### ISSUE THREAD

**Issue by MaximilianRothstein** [ankitrohatgi/WebPlotDigitizer#246]
Hello, I am using WebPlotDigitizer to digitize an infrared (IR) spectroscopy plot.

The wavenumbers are plotted on the x-axis. It first appears to be linear (i.e. the step between 4000 cm-1 and 3000 cm-1 is the same distance as 2000 cm-1 to 1000 cm-1, thus making WebPlotDigitizer work). However, (due to tradition), this axis is non-linear and leads to imprecise and wrong extractions. The y-axis is not affected.

<img width="1400" alt="Screenshot 1 at 4000" src="https://user-images.githubusercontent.com/55761331/108283450-8d49a380-7183-11eb-85c5-d7621c4b1fbe.png">

<img width="1400" alt="Screenshot 2 at 500" src="https://user-images.githubusercontent.com/55761331/108283536-b79b6100-7183-11eb-8b44-15f852d664a9.png">

In the screenshots above, the x-values towards the calibration points (4000 and 500) are precise.

However, if a point is selected in the middle of the axis, the x-value determined by WebPlotDigitizer is dramatically incorrect (i.e. it should be 2000, but WebPlotDigitizer erroneously thinks it is 2600).

<img width="1400" alt="Screenshot 3 at 2000, showing 2600" src="https://user-images.githubusercontent.com/55761331/108283763-2d073180-7184-11eb-99d4-e8ba8110b801.png">

This mismatch negatively influences the dataset.

I am plotting the results with R, and maybe I can look into setting the axis more precisely in R, i.e. shifting the axis.

However, a possible fix would be to add more calibration points, i.e. let the user add more calibration points.

**Comment by nbehrnd** [comment]
[SDBS](https://sdbs.db.aist.go.jp/sdbs/cgi-bin/cre_index.cgi) is not the sole source freely available on the net with experimental IR data.  A complementary database for data of this type _already digitized_ is the NIST webbook chemistry, which for this compound offers visual representation as .svg as well as JCAMP-DX data in the typical [mid-infrared](https://webbook.nist.gov/cgi/cbook.cgi?ID=C50782&Units=SI&Type=IR-SPEC&Index=1#IR-SPEC) (4000 -- 670 wavenumbers) as well what is considered [THz](https://webbook.nist.gov/cgi/cbook.cgi?ID=C50782&Units=SI&Mask=100#THz-IR-Spec).

I speculate (because of cheminformatics' relevance to IR spectroscopy), there are multiple modules in R to work with this format right away.  If not, and if there is no need to process batches of files into «x-y format», [Norbert Haider](http://merian.pch.univie.ac.at/pch/nh_info.html) (University of Vienna) wrote a lightweight *IRView* program to inspect and translate JCAMP-DX into a tabulator separated format ([Windows executable](http://merian.pch.univie.ac.at/pch/download/spectroscopy/irview32.exe)); which extends functionalities already present in his [jdxview](http://merian.pch.univie.ac.at/%7Enhaider/cheminf/jdxview.html).  (Compartmentalized, it equally is possible to run this gem in Linux and the wine libraries, too.)

[jko.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6000640/jko.zip)

**Comment by MaximilianRothstein** [comment]
Thank you for the links. I am aware that the NIST Chemistry Webbook has some plots already digitized. However, not for all substances, e.g. there is no IR spectrum for isobutyl acetate from the [Webbook](https://webbook.nist.gov/cgi/inchi/InChI%3D1S/C6H12O2/c1-5(2)4-8-6(3)7/h5H%2C4H2%2C1-3H3) available.

**Comment by nbehrnd** [comment]
Compared to a spectral database with access to the data recorded, the
visual representation as a .gif by SDBS lacks optical resolution.
SDBS probably was not intended to be both public and offering more
than a brief preview (which already is a lot) to limit bandwidth.
Which equally could be a reason why the limit is set to 50 sets per
day.

I may have a look on the first IR later to check if splitting the
.gif into two separate projects and subsequent use of the box-method
yields a better result, than the default mask.

---

Independent from this, if affiliated with a university, it would be
worth to check if they have access to spectral databases.  They could
be:

+ in print (e.g., Sadtler, Aldrich, Hummel) so a high-resolution scan
  may offer better «raw data» for the digitizer. Complementary: The
  compilations by Pretsch idealize bands by a range, then indicate
  specific, experimentally determined positions.

+ they could be electronic for free by the chemical suppliers (e.g.,
  Aldrich), or part of the spectrometer's software.  Speaking of
  the former, with name / structure / CAS RN you may need to look
  for multiple entries per CAS RN to identify /the/ product number
  with Aldrich's recorded IR / Raman / NMR in the lower section
  «Documents».

  Example isobutyl acetate with product number W217506 at
  https://www.sigmaaldrich.com/catalog/product/aldrich/w217506?lang=en&region=US
  to yield link
  https://www.sigmaaldrich.com/spectra/rair/RAIR000962.PDF

+ they could be in a database requiring subscription.  Ask your
  librarian / spectroscopist / analytical chemist about e.g.,
  SpecInfo; or databases organized as pointer to the data like
  Know-it-all (BioRad), SpringerMaterials, Reaxys (Elsevier), CAS.

**Comment by nbehrnd** [comment]
Given the constraints, the result of a quick digitization does not look too bad (for me).   Maybe decrease the step width further to 1 px along abscissa and ordinate, maybe smooth the appearance by a SG filter, etc.:

![concatenate](https://user-images.githubusercontent.com/19709084/108336016-821a6600-71cb-11eb-87c9-83ba43bb405d.png)

The archive below documents my approach.

[SDBS_532.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6001677/SDBS_532.zip)

**Comment by MaximilianRothstein** [comment]
Thank you for the suggestions and the approach of splitting the data.

I was able to correct the x-axis in my R plot by first removing the x-axis and then replacing it with defined ticks. WebPlotDigitizer confirmed my calculations, which I first did by hand and now the plot has a correct x-axis.
