### ISSUE TITLE
Outliers at the same locations

### ISSUE THREAD

**Issue by rsfeelsomoon** [ankitrohatgi/WebPlotDigitizer#250]
Hi,

I'm extracting data from some simple X-Y line plots. I got some outliers at the same locations for all the plots though the data points shown on the plot seem to match perfectly. Any help is appreciated!

The dots seem to match great. Note the maximum of x is 70.
![image](https://user-images.githubusercontent.com/45641746/113390611-f0178880-9346-11eb-96e4-e321dcc023d4.png)

The data extracted has some points above 70.
![image](https://user-images.githubusercontent.com/45641746/113390726-235a1780-9347-11eb-9421-6a1533adcba0.png)

The abnormal points happens at similar locations.
![image](https://user-images.githubusercontent.com/45641746/113390770-38cf4180-9347-11eb-8060-c2f21571179a.png)
![image](https://user-images.githubusercontent.com/45641746/113390781-3f5db900-9347-11eb-9162-8f16547f8c1f.png)

A sample profile I want to extract.
![image](https://user-images.githubusercontent.com/45641746/113390856-6320ff00-9347-11eb-97c9-7e325fc6afda.png)

**Comment by nbehrnd** [comment]
The very first image shown by you _looks like_ a plot simultaneously including traces and a legend.
Because the digitizer screens the image for any pixel matching the definition of colour you set, it
may happen that pixels of this legend equally are taken into consideration _as if_ they would belong
to the very trace, too.  This pitfall seems even more plausible to me because the blue and amber
trace in the subsequent examples show this not at the same position (along your ordinate):

![possible_pitfall](https://user-images.githubusercontent.com/19709084/113412702-8203ad80-93a8-11eb-85d9-fae36722f6ff.png)

Either
- run the digitization again, and remove theses points erroneously attributed manually.  One such
  point is marked by the blue rectangle in the screen photo above.  For this, the  GUI dedicates a
  separate button to delete the points while seeing the whole data set.

.or.

- define your region of interest the digitizer shall work on with the tab «box».  Then, the program's 
  action will be constrained to this area.  In fact, you equally may use multiple boxes to build a mask
  if one large box would pass beyond the frontier of the legend, too.

Opting for the first approach, the digitization just worked fine (i.e., values of the abscissa less than 70
only); see the project's data below.

[test_run.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/6249369/test_run.zip)
