### ISSUE TITLE
Feature Request: Have X1 and Y1 be the same point in 2d plots

### ISSUE THREAD

**Issue by TristanHehnen** [ankitrohatgi/WebPlotDigitizer#263]
Hi!

When setting up the axis align for a 2d plot one needs to specify the x-axis and  the y-axis with two points each. In many cases both axis intersect at the origin. With the right now implemented functionality one needs to align the origin points for each axis manually. It would be nice to have the option that X1 and Y1 are treated as a single point, since they should overlap anyway.

Also: Thank you very much for this awesome software, it has helped me a lot already!

Kind regards,
Tristan

**Comment by ankitrohatgi** [comment]
Hi, they are intentionally kept separate since X1, Y1 may be the same for many plots, but it is also not the same in just as many cases. I don't want to build two different things just to save a click.

**Comment by TristanHehnen** [comment]
It is not only about to save a click but to avoid the need to manually position two points at the same location. There might not be the need to implement something completely new, only a toogle which copies the coordiates from X1 to Y1.

Anyway, thanks for your reply.

**Comment by nbehrnd** [comment]
Right after the selection of the Cartesian diagram, the splash window
symbolizes that X1 and Y1 need not to be superimposed of each other.
It suffices if X1 and X2 are accurate enough about the reading of the
abscissa, and Y1 and Y2 accurate enough about the ordinate.  A wide
spread of the two *per category* is beneficial for precision, though.

So far -- in my experience -- the definition of four points of
reference instead of three was not issue for mine, especially if the
image to digitize was of resolution good enough for the intended work
(with the eventually digitized data).

If you have multiple plots sharing same outer dimension and layout,
then there probably is a way to run

+ once the digitization manually up and including the generation of
  the archive about the digitization.  Subsequently,

+ extract the relevant information from one of the JSON files, and
  use a script to run the digitizer of this batch of images to
  digitize.

This because the first pull down menu includes an entry "run a
script".  Either manual, project blog, or issue tracker possibly
include information how to proceed along this route; if this isn't
the case, this could yield an interesting addition to the
documentation.

**Comment by TristanHehnen** [comment]
Alright, thanks to both of you for the replies!
