### ISSUE TITLE
Crosshair position switches to scientific notation

### ISSUE THREAD

**Issue by dev3011** [ankitrohatgi/WebPlotDigitizer#264]
I am using the downloaded version 4.4 on Win10.

When I set the axes the crosshair position is indicated in notation with comma.
![comma notation](https://i.imgur.com/K2PTZBM.png)
Sometimes it suddenly switches to scientific notation.
![scientific notation](https://i.imgur.com/GBGYEC8.png)

This sometimes happens after saving the data as csv or json but sometimes even happens right after setting the axes. I found no way to revert back to 'normal' notation other than restarting the project.

**Comment by ankitrohatgi** [comment]
The coordinates are in 'normal' decimal notation when the values are in pixels (either not yet calibrated or using image axes).

After calibration, the numbers represent the data value at the mouse location and not pixels. Since the data coordinates can be any magnitude from extremely large values to extremely small values (depending on what's in the plot), it is easier to format those values using the exponential notation since then there's no special logic needed to switch formatting based on the magnitude (most old school calculators do the same).

**Comment by ankitrohatgi** [comment]
Also - there are cases when the active selections don't map to an axes calibration (e.g. while measuring angles) and in those cases these values switch back to showing pixels.

**Comment by dev3011** [comment]
Thank you for the clarification. My issue with this was that when I loaded another picture and then have to set the axes it did not switch back to decimal notation. But I found the "Remove Grid" option now which solves this. Thanks for the awesome tool!
