### ISSUE TITLE
Feature Request: Standardized Build System

### ISSUE THREAD

**Issue by Joedang** [ankitrohatgi/WebPlotDigitizer#269]
## Intro

It occurs to me that some (many?) people may want to host WebPlotDigitizer locally, rather than visiting `https://apps.automeris.io/wpd/`. There are many reasons for this. Someone could lack consistent internet access. They could be working with highly sensitive data, where it's unacceptable to assume the code served by automeris.io is actually what's on the GitHub repo. 

It's great that the repo does include the tools necessary to do this, however the build process leaves a lot to be desired. I suspect very few people have actually gone to the trouble of doing this, especially those in my second example. Using a more standardized/automated build system would make WPD more accessible and would probably lead to distros actually adopting the Electron app.

### README -> configure -> make
The "standard" interface for building open-source projects  tends to be `./configure && make && make install`. So, there's some file, either `INSTALL` or `README`, that 

- explains the basic build commands, 
- lists the build-time dependencies,
- lists the run-time dependencies, 
- calls out pitfalls (like how to build for different OSes), and 
- explains any/all flags to `configure`. 

`configure` is used to tweak any variables in the Makefile (such as the install directory), and the Makefile contains recipes for different types of builds. 

#### make targets for WPD

So for example, WebPlotDigitizer would probably have a few different `make` targets for compiling the JS, building the electron app, building the webserver, running the webserver, et cetera. (It would be very nice to have a target that creates a monolithic HTML file, but that's an issue for another time.)

#### breaking up the work

The Makefile does not need to handle the entire build process in one monolithic file. Large projects typically have sub-directories for their various sub-components, each with their own Makefile that can be kicked off as part of a Makefile further up the hierarchy. This is especially true for projects that pull dependencies as Git submodules.

#### faster builds

A big advantage of using `make` is that it keeps track of which components are up-to-date with the components on which they depend. For example, if you're modifying the Electron wrapper and rebuilding it, it's not going to recompile all the Clojure every time. So, this could help make the development process easier.

## Issues with the current build system
It seems that anyone wishing to build their own copy of WPD would need to stumble through the various directories guessing which shell scripts to run. Some READMEs explain which scripts to run, but many do not. If a human needs to do something manually, it should be called out in a README. (These build tasks are much better suited to a Makefile anyways.)

### wget
Many of the build scripts `wget` a file from a URL and then run it. In my humble opinion, this is a huge party foul. 

#### security hole

Some links, like the link to `tarballjs` in `app/thirdparty/getThirdparty.sh` are not tied to a specific version. So, if the maintainer of `tarballjs` were to release a non-backwards-compatible change or if their account/domain were to be hijacked, this would be a big stability/security problem. This makes eliminating any `wget` commands is especially important in any automated build system, since people will usually be `root` when installing the Electron app or web server!

This also just gives the impression that WPD is trying to hide some of its code, which isn't good. Downloading these things from a URL is certainly acceptable as a last resort, but it shouldn't be the default.

These dependencies need to either be listed as system-level dependencies, so the user can install them through their system package manager. Alternatively, they could be Git submodules, so they're tied to a specific commit.

## Meta

Sorry for writing such a long and rambling issue. I hope it was helpful and made sense. If nobody wants to dig into this, I might be interested in taking it on as a side project in a few months. Would people be interested in an automated build system using `make`?

**Comment by ankitrohatgi** [comment]
I'm well aware of the common build and dependency management systems and many decisions made here are either intentional or just something I haven't gotten to yet. All of what you see today is likely to change at some point in the future.

Since this is a primarily web based application (or electron based for desktop), I do not expect typical users of this application to be building the code unless they are actively developing it (this is similar to things like Slack, VSCode etc.). The number of people wanting to self-host is relatively small, and I am expecting that most of those advanced users are capable of dealing with a non-standard build system.

This is an opensource software that I develop in my scarce spare time and for this reason I consider myself as the primary consumer of the build system. I mainly provide the code and build scripts for transparency. The simple and stupid set of scripts have allowed me to maintain this tool for 10+ years now with just part time effort (often not looking at this code for 10+ months). I can dive into this code and quickly iterate on a feature without any issues. The frontend and backend is very decoupled and rarely do I feel the need for partial builds. If I feel the need for a better system, then I can change it in the future.

Also, the `./configure && make && make install` is typical for traditional opensource projects written in compiled languages like C, C++ etc., but most web based software use tools like `npm`, `yarn` etc. for build and dependency management. I had avoided using these tools until recently because none of them were very stable when I started this project. Things are a lot more stable now and I have started switching some parts (e.g. `getThirdparty.sh` was removed just last night). I might clean up things more as I get time.

As for `tarballjs`, if you look at the URL, I am the primary (and only) maintainer of that code and it is also hosted on my GitHub just like WebPlotDigitizer. I have not yet felt the need to pin to specific versions of that code (I can in the future, if needed).

**Comment by Joedang** [comment]
Thanks for taking the time to read and respond. I'm glad this build system is working for you, and I'm very thankful you've taken the time to create WPD and make it freely accessible. 

I think the cost/benefit tradeoff of cleaning up the build system might be a little chicken-and-egg. Reducing the barrier of entry to creating pull requests would also reduce the amount of code for you to write and repair, because there will be more contributors available to close issues. However, there aren't going to be many people making those PRs until the barrier of entry is lower. 

Yeah, `make` is definitely more common for older languages, but still works for anything. My main reason for suggesting it was that, at least in my experience, it's far more common to encounter as a user. (I'm personally not a fan of bespoke, language-specific build systems because, as a user, I'm typically learning that build system and then never using it again.)

I think that for the use-case of highly sensitive data, it would make a lot of sense to have a more accessible non-web version. 

If/when I have time, after my life calms down, would you be interested in a PR to switch to a more cohesive build system (or additions to the README that spell out the build process)?

**Comment by ankitrohatgi** [comment]
I'm guessing that you missing that the build process is spelled out here which is linked to the README: https://github.com/ankitrohatgi/WebPlotDigitizer/blob/master/DEVELOPER_GUIDELINES.md
