### ISSUE TITLE
Calibration can sometimes give nonsensical results

### ISSUE THREAD

**Issue by illbebach** [ankitrohatgi/WebPlotDigitizer#302]
I used the web interface at https://apps.automeris.io/wpd/ today.

Setting the scales on the attached image (870x543) to deal with the scales leads to NaN in the Y axis.

![Screen Shot](https://user-images.githubusercontent.com/1385858/224577747-f7348ad1-d1f1-49ce-8cfa-54f9a5f65354.png)

I clicked on the axes correctly, and entered values   28156 44227 for the X axis.  They correspond to 1/31/77 and 1/31/21 in Excel.  Then I entered 0 an 18 for the y axis.  When I do so, all the Y values are NaN.  If I use values 0 and 1800 for the Y axis, and no other changes, the coordinates come out as expected.

**Comment by nbehrnd** [comment]
For one, the abscissa is about dates, and hence, digitization should account for this, too.  The widget (see step02.png attached in the .zip) offers for example the YYYY/MM/DD format.  For two, the trace `10YR` is easier recovered with the manual color pick on the trace in question, than with the colors identified automatically (step06/07 vs 08/09).  In both cases (black / 2yr, and brownish / 10yr), the color tolerance can be constrained to 50, or even 20.  Reference points need not to overlap, i.e. to use the tic on 2% as low reference of the ordinate equally is fine.

The image to process is of low resolution, and lacks ticks on the abscissa.  Hence the error to pick the reference points for the time domain likely is greater, than for the percentage.  Nevertheless, the digitizer collects the data; the reconstruction - e.g. with [gnuplot](http://gnuplot.info/) - bears similarity to the original illustration.  It still could be improved a lot.  Do you a) can access the original illustration of higher optical resolution?  Maybe it is from a publication embedded into a pdf - either record a screen photo of higher resolution, or use e.g., [inkscape](https://inkscape.org/) to extract the embedded illustration (import of the page of interest, ungroup the elements on the page, remove unwanted elements, eventual export of the plot as high resolution .png for the digitization).  b) Try a algorithm different to `averaging window` - for example (fixed) `x step`, and c) test a smaller increment (e.g. `5 px` instead of `10 px`).

![reconstruction](https://user-images.githubusercontent.com/19709084/224652569-92303211-a474-465e-a699-8c58890d1e39.png)


[testcase.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/10955340/testcase.zip)
