### ISSUE TITLE
Screenshot option for capturing images

### ISSUE THREAD

**Issue by dlebauer** [ankitrohatgi/WebPlotDigitizer#36]
My standard workflow for using a plot digitizer is to 
1. find a plot in a pdf
2. take a screenshot 
3. save as jpg
4. upload to digitizer
5. align axes and extract points

If there were an option to directly capture a screenshot, this would circumvent steps 3 and 4. It may seem small, but both of these steps require navigating to the folder containing the image, which can get tedious.

**Comment by ankitrohatgi** [comment]
If you use Google Chrome, then you can copy an image from the PDF (e.g. using the snapshot tool in Adobe Reader) and then pressing Ctrl+V (on Windows) should paste the image into the app.

But I agree, this is not something that will work for everyone. This sort of feature would be pretty straightforward if this was a desktop program, but since it's running inside a browser, I am not sure if implementing this will be possible. I was somewhat aware of this issue, but didn't pay too much attention to it since no one had pointed this out till now. So thanks for bringing this up, I'll see if I can do something.

**Comment by rainwoodman** [comment]
We should be able to get this working in firefox after this bug is fixed:

https://bugzilla.mozilla.org/show_bug.cgi?id=906420

**Comment by ankitrohatgi** [comment]
That is great! Thanks for sharing that bug report. I was wondering why it never worked in Firefox.

**Comment by ankitrohatgi** [comment]
Seems to work now, closing issue.
