### ISSUE TITLE
during moving points

### ISSUE THREAD

**Issue by lockheedlocker** [ankitrohatgi/WebPlotDigitizer#56]
after adding any point, and try to move it precisly with the keyboard arrows, the point moves BUT the cross return to it last place putted by the mouse letting me not able to be sure if i reached the desired place or not.

ps. i used the application one week ago, and this issue was not there .

**Comment by ankitrohatgi** [comment]
Nothing has changed in the last week, so I'm surprised you're seeing this behavior. I will take a look in a couple of days and get back to you.

**Comment by lockheedlocker** [comment]
Okay I will try on another browser, may be anything

**Comment by ankitrohatgi** [comment]
What browser are you using? if you can share the OS and browser version number, then that would be useful too.

**Comment by lockheedlocker** [comment]
Am using Windows 10, Google Chrome 46
And i tried Microsoft edge and no trace for the problem

I don't know what happened to chrome?
What do you think?

**Comment by ankitrohatgi** [comment]
I am traveling this week so I don't have access to my computer, but I can check tomorrow. It is possible chrome changed something with an update. I have a Windows 10 machine I can try this on.

**Comment by lockheedlocker** [comment]
Okay
Have fun

Best wishes

I hope hear from you tomorrow

**Comment by ankitrohatgi** [comment]
I just tried adding points in Chrome 47.0.2526.73 on Windows 10 and I don't see any issues. When you add a point and then hit the keyboard cursor keys, the cross in the zoom window should be directly over the point and the point itself should move. On the main screen however, the cross will remain wherever the mouse was left last. This is expected behavior.

To test if your adjustments are working as you expect, I suggest just adding one data point and comparing the values in the CSV before and after adjustment.

**Comment by lockheedlocker** [comment]
May be java issue
