### ISSUE TITLE
Handling error bars

### ISSUE THREAD

**Issue by TimLehner** [ankitrohatgi/WebPlotDigitizer#60]
Would it be possible to automatically detect errorbars and ignore them as points?

Consider an input image generated using python: 
![example_errorbars](https://cloud.githubusercontent.com/assets/8646034/13427192/45d4e93a-dfaa-11e5-9591-9ff9a0730b08.png)

The output selects far too many points, because the error-bar is necessarily the same colour as the data points. This can be seen below
![result](https://cloud.githubusercontent.com/assets/8646034/13427193/4894c136-dfaa-11e5-8b72-23f49518883d.png)

How should I handle data of this form?

**Comment by ankitrohatgi** [comment]
Error bars are hard to detect in a automated manner. I do not have a good solution at the moment. However, if you are only interested in the values along the curve, then please increase delta_y parameter to a large number (e.g. 1000) so that the averaging is done over a larger vertical slice and you will not get multiple points like you have shown.
