### ISSUE TITLE
Feature Request:  Work with Region of an Image

### ISSUE THREAD

**Issue by billdenney** [ankitrohatgi/WebPlotDigitizer#69]
I often work with scanned .pdf files as my input.  There are many tools that will easily extract the images from .pdf files, so I have in my workflow a simple way to get all the images out.  But, I prefer to have each figure separately managed within my digitization workflow.  For example, I only want to see figure 1 while digitizing figure 1 and not the whole page.

Could a "crop" feature be added where upon loading the image, the user can choose the region of the image to look at?

**Comment by ankitrohatgi** [comment]
Hi Bill,

I did have a crop function in some older versions of the app (2.x), but I removed it when the code was reworked for version 3.0. My plan was to reintroduce crop as part of a set of image editing features at some point in the future. I'll keep this issue open till that's completed.

Regards,
Ankit

**Comment by flutefreak7** [comment]
Perhaps tangentially related would be the ability to select which page of a pdf to work with. Since PDF's are supported this would be a natural pre-processing step similar to cropping, and saves the user from having to either extract the page into a 1-page PDF or extract the image -- both of which create unnecessary intermediate files.

**Comment by ankitrohatgi** [comment]
I agree. I also plan on adding some way to select a particular PDF page in multi-page PDF documents in the future.

**Comment by billdenney** [comment]
This was effectively fixed when multiple axes were allowed per page.
