### ISSUE TITLE
Add log log scale

### ISSUE THREAD

**Issue by Eztarok** [ankitrohatgi/WebPlotDigitizer#85]
Hello,

I'd like to scan plots with log(log()) scale on Y axis. I think it can easily taken into account by using a script to change the transformation equation but i I know almost nothing about JS. 
Can anyone help me about that ?

Thanks!

**Comment by ankitrohatgi** [comment]
Hello,

If you really have log(log()), then you might have the axes labeled as 10^1, 10^10, 10^100 and so on (if not these exact labels, but similarly increasing scale).

In this case, you might not need to write a new script if you follow the steps below:

1. During axes calibration, enter (Y1,Y2) as (log10(label at Y1), log10(label at Y2)), so if you had Y1 = 10^1 and Y2 = 10^1000, then you enter 1 and 1000. Make sure you select the log-scale option for Y axes.

2. Digitize the chart normally and download the CSV file.

3. Calculate 10^(Y) of the values that you obtain finally. These should be the Y values you are after.

If you are able to share the chart (here or via email), then I might be able to help you better.

Regards,
Ankit

**Comment by Eztarok** [comment]
Hello, 

Thank you for your reply, the idea is good :) However, the problem is that my Y axis goes from 1e-1 to 1e5 and I can't use negative value for log-scale axis.

**Comment by ankitrohatgi** [comment]
Are you sure you have log of the values plotted on a LOG scale in Y-axes? I have never seen a chart like this. I have seen people plot log of the values on a LINEAR scale. In which case, you can still do above without checking the "log" option for Y axis in WPD.

IF you really have log of values plotted on a log scale and you have 1e-1, then instead of entering log(label), enter log(100*label). Finally, just do 10^(WPD y value)/100.

I can provide further help if you can share the chart, otherwise this is all I have.
