### ISSUE TITLE
Scaling is Off

### ISSUE THREAD

**Issue by Vicente451** [ankitrohatgi/WebPlotDigitizer#90]
Verification of Digitized values returned compared to original chart are off by more than 5%. This may not seem to be a big error but is very apparent. The original chart is square and regular so I expected accuracy to be better. Also the errors appear to be biased in one direction only. Measured values are lower than chart values. This makes me believe that there may be some issues with the original digitized scaling of the  plot. Chart is a vertical Bar Chart, scaled between 0 to 800. Also the error
![copper_warehousestocks2008-10](https://cloud.githubusercontent.com/assets/28846974/26287456/957a43f0-3e30-11e7-9866-ac8f78887873.gif)

**Comment by ankitrohatgi** [comment]
The bar chart scaling tries to account for rotation as well so in this case you have to be extra careful when aligning the axes. Since there is no vertical line along y-axis, it is easy to pick a point the two calibration points that are not exactly vertically aligned. For now, I suggest turning on the extended crosshair option (next to zoom buttons) when picking the two calibration points. But I think I should add an extra option during calibration that makes the scaling ignore rotation for these type of charts.

**Comment by Vicente451** [comment]
Thanks for the quick response.

Yes an option to select ‘Chart is Strait/Square’ and/or selecting a third axis point along the X-Axis would solve this problem. 

Now that I know the issue I will try tansforming my data, already collected, based on a rotational error.

Vince

**Comment by ankitrohatgi** [comment]
I have added an option for this during bar chart calibration in the latest release.

**Comment by Vicente451** [comment]
Nice!

 

I still think you ought to consider labeling data points starting at 1 (not zero).

But thanks for your nice tool, and your interest in improving it.

Vince
